version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope

